---
  AWSTemplateFormatVersion: "2010-09-09"
  Mappings:
    Region2AMI:
      !Include http://localhost:9999/synopsis.json
  Resources:
    Instance:
      Type: AWS::EC2::Instance
      Properties:
        ImageId: !FindInMap [Region2AMI, !Ref AWS::Region, AMI]
        UserData:
          Fn::Base64:
            Fn::Sub:
              !Include { type: literal, location: userdata.sh }
