name: tests

on:
  workflow_call:
  pull_request:
    branches: ["master"]

jobs:
  test:
    strategy:
      matrix:
        node-version: ['18.x', '20.x', '22.x']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          # cache: "npm" # needs lockfile if enabled

      - run: npm install
      - run: npm run lint
      - run: npm test
